---
- name: install elastic
  gather_facts: false
  hosts: node2
  become: True
  tasks:
          - name: Add apt_key
            apt_key:
                    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
                    state: present

          - name: Install APT repository
            package:
                    name: apt-transport-https
                    state: present

          - name: Save repo
            lineinfile:
                    path: /etc/apt/sources.list.d/elastic-7.x.list
                    line: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
                    state: present

          - name: Install elasticseach
            package:
                    name: elasticsearch
                    state: present


...
