---

- name : Setup VM Elastic Data Engineer 
  hosts: bootcamp
  become : True
  vars :
          ip_bootcamp : 10.11.200.103
  tasks:
          - name : Install Pachages needed
            apt: name= 
            with_items:
                    - wget
                    - curl
                    - openssl

          - name : install elasticsearsh 
            apt:
                    deb : https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb

                    
          - name : config elastic network
            replace:
                    path: /etc/elasticsearch/elasticsearch.yml
                    regexp: '#network.host: 192.168.0.1'
                    replace: 'network.host: _global_'

          - name : config seed network
            replace:
                    path: /etc/elasticsearch/elasticsearch.yml
                    regexp: '#discovery.seed_hosts: ["host1", "host2"]'
                    replace: 'discovery.seed_hosts: ["{{ ip_bootcamp }}"]'
 
          - name : starte elastic
            systemd :
                    name : elasticsearch
                    enabled : yes
                    state: started


          - name : install kibana
            apt :
                    deb : https://artifacts.elastic.co/downloads/kibana/kibana-7.5.1-amd64.deb

          
          - name : config ip kibana
            replace:
                    path: /etc/kibana/kibana.yml
                    regexp: '#server.host: "localhost"'
                    replace: 'server.host: "{{ ip_bootcamp }}"'

                    
                    #          - name: Create the log directory if it does not exist
                    #            file:
                    #                    path: /var/log/kibana
                    #                    state: directory
                    #                    group: root
                    #                    owner: kibana
                    #                    mode: '0765'
  
                    #          - name: Touch the log file
                    #            file:
                    #                    path: /var/log/kibana/kibana.log
                    #                    state: touch
                    #                    owner: kibana
                    #                    group: root
                    #                    mode: u=rwx,g=wr,o=r

                    #          - name : config logging kibana
                    #            replace:
                    #                    path: /etc/kibana/kibana.yml
                    #                    regexp: '#logging.dest: stdout'
                    #                    replace: 'logging.dest: /var/log/kibana/kibana.log' 

                    #          - name : config kibana-elastic connexion
                    #            replace:
                    #                    path: /etc/kibana/kibana.yml
                    #                    regexp: '#elasticsearch.hosts: ["http://localhost:9200"]'
                    #                    replace: 'elasticsearch.hosts: ["http://localhost:9200"]'
                   
          - name : start kibana
            systemd:
                    name : kibana
                    enabled: yes
                    state : started
 
