---
es_cluster_name: my_application
es_path_data: /var/lib/elasticsearch
es_path_log: /var/log/elasticsearch
es_bootstrap_memory_lock: true
es_node_data : true
es_node_master: false
es_node_ml: false
es_node_jvm_mem: "500m"
...
