---
# clean the play < add conditions to reach multiple OS >
# Create a role for this need 
- name: system config
  gather_facts: False
  hosts: all
  become: True
  vars:
          open_files: 65536
          num_thread: 4096
          swap: 1
          size_file: "unlimited"
  tasks:

          - name: setup swap
            lineinfile:
                    path: "/etc/sysctl.d/99-swappiness.conf"
                    line: "vm.swappiness={{swap}}"
                    state: present
                    create: True
            notify: Reload swap

         #- name: "set swapatoff"
         #  shell: "cat /proc/sys/vm/swappiness && echo '{{ swap }}' > /proc/sys/vm/swappiness"
         #  register: out
         #  changed_when: out.stdout|int != swap 

          - name: Increase file descriptors
            lineinfile:
                    path: /etc/security/limits.conf
                    line: "elasticsearch - nofile {{ open_files }}"
                    state: present

          - name: Increase max file size descriptors
            lineinfile:
                    path: /etc/security/limits.conf
                    line: "elasticsearch - fsize {{ size_file }}"
                    state: present

          - name: Increase threads
            lineinfile:
                    path: /etc/security/limits.conf
                    line: "elasticsearch - nproc {{ num_thread }}"
                    state: present

          # allow user 'elasticsearch' mlockall 'mmap'
          - name: Give permission to elasticsearch user to lock hard memory
            lineinfile:
                    path: /etc/security/limits.conf
                    line: "elasticsearch hard memlock unlimited"
                    state: present

          - name: Give permission to elasticsearch user to lock soft memory
            lineinfile:
                    path: /etc/security/limits.conf
                    line: "elasticsearch soft memlock unlimited"
                    state: present

        # dosen't work for raspberry
        #   - name: create file  Memory lock
        #     lineinfile:
        #                 path: /usr/lib/systemd/system/elasticsearch.service
        #                 line: "LimitMEMLOCK=infinity" 
        #                 state: present
        #                 insertafter: "[Service]"
        #     notify: Deamon Reload

          - name: Create Dir
            file:
                    path: /etc/systemd/system/elasticsearch.service.d
                    mode:  0755
                    owner: root
                    group: root
                    state: directory

          - name: Set Memory lock
            lineinfile:
                    path: /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf
                    line: "LimitMEMLOCK=infinity" 
                    state: present
                    insertafter: "[Service]"
            notify: Deamon Reload

# uncomment the [# session    required   pam_limits.so] in the /etc/pam.d/su in ubuntu distrub

          - name: increase the limits of virtual mem
            lineinfile:
                    path: /etc/sysctl.conf
                    line: "vm.max_map_count=262144"
                    state: present

          - name: check vm_map_count
            shell: "sysctl vm.max_map_count"
            register: out

          - name: Check if the limit are okey
            assert:
                    that:
                            out.stdout == "vm.max_map_count = 262144"

  handlers:
          - name: Deamon Reload
            systemd:
                    daemon_reload: True
          - name: Reload swap
            shell: swapoff -av && swapon -av
